// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/sharding/v1/sharding.proto

package shardingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRequest_Operation int32

const (
	WatchRequest_ALL     WatchRequest_Operation = 0
	WatchRequest_INSERT  WatchRequest_Operation = 1
	WatchRequest_UPDATE  WatchRequest_Operation = 2
	WatchRequest_DELETE  WatchRequest_Operation = 3
	WatchRequest_REPLACE WatchRequest_Operation = 4
)

// Enum value maps for WatchRequest_Operation.
var (
	WatchRequest_Operation_name = map[int32]string{
		0: "ALL",
		1: "INSERT",
		2: "UPDATE",
		3: "DELETE",
		4: "REPLACE",
	}
	WatchRequest_Operation_value = map[string]int32{
		"ALL":     0,
		"INSERT":  1,
		"UPDATE":  2,
		"DELETE":  3,
		"REPLACE": 4,
	}
)

func (x WatchRequest_Operation) Enum() *WatchRequest_Operation {
	p := new(WatchRequest_Operation)
	*p = x
	return p
}

func (x WatchRequest_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchRequest_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sharding_v1_sharding_proto_enumTypes[0].Descriptor()
}

func (WatchRequest_Operation) Type() protoreflect.EnumType {
	return &file_proto_sharding_v1_sharding_proto_enumTypes[0]
}

func (x WatchRequest_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchRequest_Operation.Descriptor instead.
func (WatchRequest_Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_sharding_v1_sharding_proto_rawDescGZIP(), []int{7, 0}
}

// Document represents a MongoDB document with optimized payload encoding.
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // MongoDB _id as string
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`                                                                       // Target collection name
	Database      string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`                                                                           // Target database name
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // BSON-encoded document body (avoids UTF-8 overhead)
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Lightweight metadata (shard key hints, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_sharding_v1_sharding_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Document) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Document) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Document) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// InsertRequest for single document insertion.
type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharding_v1_sharding_proto_rawDescGZIP(), []int{1}
}

func (x *InsertRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

// InsertResponse confirms insertion.
type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedId    string                 `protobuf:"bytes,1,opt,name=inserted_id,json=insertedId,proto3" json:"inserted_id,omitempty"`
	Shard         string                 `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`                           // Which shard received the document
	LatencyUs     int64                  `protobuf:"varint,3,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"` // Server-side latency in microseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_sharding_v1_sharding_proto_rawDescGZIP(), []int{2}
}

func (x *InsertResponse) GetInsertedId() string {
	if x != nil {
		return x.InsertedId
	}
	return ""
}

func (x *InsertResponse) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *InsertResponse) GetLatencyUs() int64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

// QueryRequest for document queries.
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter        []byte                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"` // BSON-encoded filter (bytes for performance)
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int32                  `protobuf:"varint,5,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharding_v1_sharding_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *QueryRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *QueryRequest) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

// QueryResponse returns matching documents.
type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	LatencyUs     int64                  `protobuf:"varint,3,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"`
	TargetedShard string                 `protobuf:"bytes,4,opt,name=targeted_shard,json=targetedShard,proto3" json:"targeted_shard,omitempty"` // Empty if scatter-gather
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_sharding_v1_sharding_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *QueryResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *QueryResponse) GetLatencyUs() int64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

func (x *QueryResponse) GetTargetedShard() string {
	if x != nil {
		return x.TargetedShard
	}
	return ""
}

// BulkInsertRequest for client-streaming bulk ingestion.
type BulkInsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Documents     [][]byte               `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`                         // Each element is a BSON-encoded document
	BatchNumber   int32                  `protobuf:"varint,4,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"` // Sequence number for ordering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkInsertRequest) Reset() {
	*x = BulkInsertRequest{}
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkInsertRequest) ProtoMessage() {}

func (x *BulkInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkInsertRequest.ProtoReflect.Descriptor instead.
func (*BulkInsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharding_v1_sharding_proto_rawDescGZIP(), []int{5}
}

func (x *BulkInsertRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *BulkInsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BulkInsertRequest) GetDocuments() [][]byte {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *BulkInsertRequest) GetBatchNumber() int32 {
	if x != nil {
		return x.BatchNumber
	}
	return 0
}

// BulkInsertResponse summarizes the bulk operation.
type BulkInsertResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalInserted   int64                  `protobuf:"varint,1,opt,name=total_inserted,json=totalInserted,proto3" json:"total_inserted,omitempty"`
	BatchesReceived int32                  `protobuf:"varint,2,opt,name=batches_received,json=batchesReceived,proto3" json:"batches_received,omitempty"`
	TotalLatencyUs  int64                  `protobuf:"varint,3,opt,name=total_latency_us,json=totalLatencyUs,proto3" json:"total_latency_us,omitempty"`
	PerShardCount   map[string]int64       `protobuf:"bytes,4,rep,name=per_shard_count,json=perShardCount,proto3" json:"per_shard_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Distribution across shards
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BulkInsertResponse) Reset() {
	*x = BulkInsertResponse{}
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkInsertResponse) ProtoMessage() {}

func (x *BulkInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkInsertResponse.ProtoReflect.Descriptor instead.
func (*BulkInsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_sharding_v1_sharding_proto_rawDescGZIP(), []int{6}
}

func (x *BulkInsertResponse) GetTotalInserted() int64 {
	if x != nil {
		return x.TotalInserted
	}
	return 0
}

func (x *BulkInsertResponse) GetBatchesReceived() int32 {
	if x != nil {
		return x.BatchesReceived
	}
	return 0
}

func (x *BulkInsertResponse) GetTotalLatencyUs() int64 {
	if x != nil {
		return x.TotalLatencyUs
	}
	return 0
}

func (x *BulkInsertResponse) GetPerShardCount() map[string]int64 {
	if x != nil {
		return x.PerShardCount
	}
	return nil
}

// WatchRequest for bidirectional change stream.
type WatchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Database        string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection      string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Filter          []byte                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"` // BSON pipeline filter
	OperationFilter WatchRequest_Operation `protobuf:"varint,4,opt,name=operation_filter,json=operationFilter,proto3,enum=sharding.v1.WatchRequest_Operation" json:"operation_filter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharding_v1_sharding_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *WatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WatchRequest) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *WatchRequest) GetOperationFilter() WatchRequest_Operation {
	if x != nil {
		return x.OperationFilter
	}
	return WatchRequest_ALL
}

// WatchEvent streams real-time changes.
type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"` // insert, update, delete, replace
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	FullDocument  []byte                 `protobuf:"bytes,3,opt,name=full_document,json=fullDocument,proto3" json:"full_document,omitempty"` // BSON-encoded full document (bytes for speed)
	Collection    string                 `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	Shard         string                 `protobuf:"bytes,5,opt,name=shard,proto3" json:"shard,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // Cluster time in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharding_v1_sharding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_proto_sharding_v1_sharding_proto_rawDescGZIP(), []int{8}
}

func (x *WatchEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *WatchEvent) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *WatchEvent) GetFullDocument() []byte {
	if x != nil {
		return x.FullDocument
	}
	return nil
}

func (x *WatchEvent) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WatchEvent) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *WatchEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_proto_sharding_v1_sharding_proto protoreflect.FileDescriptor

const file_proto_sharding_v1_sharding_proto_rawDesc = "" +
	"\n" +
	" proto/sharding/v1/sharding.proto\x12\vsharding.v1\"\xee\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.sharding.v1.Document.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\rInsertRequest\x121\n" +
	"\bdocument\x18\x01 \x01(\v2\x15.sharding.v1.DocumentR\bdocument\"f\n" +
	"\x0eInsertResponse\x12\x1f\n" +
	"\vinserted_id\x18\x01 \x01(\tR\n" +
	"insertedId\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\tR\x05shard\x12\x1d\n" +
	"\n" +
	"latency_us\x18\x03 \x01(\x03R\tlatencyUs\"\x8c\x01\n" +
	"\fQueryRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\fR\x06filter\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x05 \x01(\x05R\x04skip\"\xab\x01\n" +
	"\rQueryResponse\x123\n" +
	"\tdocuments\x18\x01 \x03(\v2\x15.sharding.v1.DocumentR\tdocuments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"latency_us\x18\x03 \x01(\x03R\tlatencyUs\x12%\n" +
	"\x0etargeted_shard\x18\x04 \x01(\tR\rtargetedShard\"\x90\x01\n" +
	"\x11BulkInsertRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x1c\n" +
	"\tdocuments\x18\x03 \x03(\fR\tdocuments\x12!\n" +
	"\fbatch_number\x18\x04 \x01(\x05R\vbatchNumber\"\xae\x02\n" +
	"\x12BulkInsertResponse\x12%\n" +
	"\x0etotal_inserted\x18\x01 \x01(\x03R\rtotalInserted\x12)\n" +
	"\x10batches_received\x18\x02 \x01(\x05R\x0fbatchesReceived\x12(\n" +
	"\x10total_latency_us\x18\x03 \x01(\x03R\x0etotalLatencyUs\x12Z\n" +
	"\x0fper_shard_count\x18\x04 \x03(\v22.sharding.v1.BulkInsertResponse.PerShardCountEntryR\rperShardCount\x1a@\n" +
	"\x12PerShardCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xf9\x01\n" +
	"\fWatchRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\fR\x06filter\x12N\n" +
	"\x10operation_filter\x18\x04 \x01(\x0e2#.sharding.v1.WatchRequest.OperationR\x0foperationFilter\"E\n" +
	"\tOperation\x12\a\n" +
	"\x03ALL\x10\x00\x12\n" +
	"\n" +
	"\x06INSERT\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\v\n" +
	"\aREPLACE\x10\x04\"\xc9\x01\n" +
	"\n" +
	"WatchEvent\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rfull_document\x18\x03 \x01(\fR\ffullDocument\x12\x1e\n" +
	"\n" +
	"collection\x18\x04 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05shard\x18\x05 \x01(\tR\x05shard\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs2\xbe\x02\n" +
	"\x0fShardingService\x12I\n" +
	"\x0eInsertDocument\x12\x1a.sharding.v1.InsertRequest\x1a\x1b.sharding.v1.InsertResponse\x12G\n" +
	"\x0eQueryDocuments\x12\x19.sharding.v1.QueryRequest\x1a\x1a.sharding.v1.QueryResponse\x12O\n" +
	"\n" +
	"BulkInsert\x12\x1e.sharding.v1.BulkInsertRequest\x1a\x1f.sharding.v1.BulkInsertResponse(\x01\x12F\n" +
	"\fWatchUpdates\x12\x19.sharding.v1.WatchRequest\x1a\x17.sharding.v1.WatchEvent(\x010\x01B6Z4go-mongodb-sharding-poc/proto/sharding/v1;shardingv1b\x06proto3"

var (
	file_proto_sharding_v1_sharding_proto_rawDescOnce sync.Once
	file_proto_sharding_v1_sharding_proto_rawDescData []byte
)

func file_proto_sharding_v1_sharding_proto_rawDescGZIP() []byte {
	file_proto_sharding_v1_sharding_proto_rawDescOnce.Do(func() {
		file_proto_sharding_v1_sharding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sharding_v1_sharding_proto_rawDesc), len(file_proto_sharding_v1_sharding_proto_rawDesc)))
	})
	return file_proto_sharding_v1_sharding_proto_rawDescData
}

var file_proto_sharding_v1_sharding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sharding_v1_sharding_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_sharding_v1_sharding_proto_goTypes = []any{
	(WatchRequest_Operation)(0), // 0: sharding.v1.WatchRequest.Operation
	(*Document)(nil),            // 1: sharding.v1.Document
	(*InsertRequest)(nil),       // 2: sharding.v1.InsertRequest
	(*InsertResponse)(nil),      // 3: sharding.v1.InsertResponse
	(*QueryRequest)(nil),        // 4: sharding.v1.QueryRequest
	(*QueryResponse)(nil),       // 5: sharding.v1.QueryResponse
	(*BulkInsertRequest)(nil),   // 6: sharding.v1.BulkInsertRequest
	(*BulkInsertResponse)(nil),  // 7: sharding.v1.BulkInsertResponse
	(*WatchRequest)(nil),        // 8: sharding.v1.WatchRequest
	(*WatchEvent)(nil),          // 9: sharding.v1.WatchEvent
	nil,                         // 10: sharding.v1.Document.MetadataEntry
	nil,                         // 11: sharding.v1.BulkInsertResponse.PerShardCountEntry
}
var file_proto_sharding_v1_sharding_proto_depIdxs = []int32{
	10, // 0: sharding.v1.Document.metadata:type_name -> sharding.v1.Document.MetadataEntry
	1,  // 1: sharding.v1.InsertRequest.document:type_name -> sharding.v1.Document
	1,  // 2: sharding.v1.QueryResponse.documents:type_name -> sharding.v1.Document
	11, // 3: sharding.v1.BulkInsertResponse.per_shard_count:type_name -> sharding.v1.BulkInsertResponse.PerShardCountEntry
	0,  // 4: sharding.v1.WatchRequest.operation_filter:type_name -> sharding.v1.WatchRequest.Operation
	2,  // 5: sharding.v1.ShardingService.InsertDocument:input_type -> sharding.v1.InsertRequest
	4,  // 6: sharding.v1.ShardingService.QueryDocuments:input_type -> sharding.v1.QueryRequest
	6,  // 7: sharding.v1.ShardingService.BulkInsert:input_type -> sharding.v1.BulkInsertRequest
	8,  // 8: sharding.v1.ShardingService.WatchUpdates:input_type -> sharding.v1.WatchRequest
	3,  // 9: sharding.v1.ShardingService.InsertDocument:output_type -> sharding.v1.InsertResponse
	5,  // 10: sharding.v1.ShardingService.QueryDocuments:output_type -> sharding.v1.QueryResponse
	7,  // 11: sharding.v1.ShardingService.BulkInsert:output_type -> sharding.v1.BulkInsertResponse
	9,  // 12: sharding.v1.ShardingService.WatchUpdates:output_type -> sharding.v1.WatchEvent
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_sharding_v1_sharding_proto_init() }
func file_proto_sharding_v1_sharding_proto_init() {
	if File_proto_sharding_v1_sharding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sharding_v1_sharding_proto_rawDesc), len(file_proto_sharding_v1_sharding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sharding_v1_sharding_proto_goTypes,
		DependencyIndexes: file_proto_sharding_v1_sharding_proto_depIdxs,
		EnumInfos:         file_proto_sharding_v1_sharding_proto_enumTypes,
		MessageInfos:      file_proto_sharding_v1_sharding_proto_msgTypes,
	}.Build()
	File_proto_sharding_v1_sharding_proto = out.File
	file_proto_sharding_v1_sharding_proto_goTypes = nil
	file_proto_sharding_v1_sharding_proto_depIdxs = nil
}
