// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: proto/sharding/v1/sharding.proto

package shardingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShardingService_InsertDocument_FullMethodName = "/sharding.v1.ShardingService/InsertDocument"
	ShardingService_QueryDocuments_FullMethodName = "/sharding.v1.ShardingService/QueryDocuments"
	ShardingService_BulkInsert_FullMethodName     = "/sharding.v1.ShardingService/BulkInsert"
	ShardingService_WatchUpdates_FullMethodName   = "/sharding.v1.ShardingService/WatchUpdates"
)

// ShardingServiceClient is the client API for ShardingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShardingService provides high-performance access to the sharded MongoDB cluster.
type ShardingServiceClient interface {
	// InsertDocument inserts a single document (unary).
	InsertDocument(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// QueryDocuments queries documents with a filter (unary).
	QueryDocuments(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// BulkInsert accepts a stream of document batches for high-throughput ingestion.
	// Client sends batches of ~1000 docs, server responds with total count.
	BulkInsert(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BulkInsertRequest, BulkInsertResponse], error)
	// WatchUpdates maintains a bidirectional stream for real-time change events.
	// Client sends watch filters, server streams matching change events.
	WatchUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchRequest, WatchEvent], error)
}

type shardingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShardingServiceClient(cc grpc.ClientConnInterface) ShardingServiceClient {
	return &shardingServiceClient{cc}
}

func (c *shardingServiceClient) InsertDocument(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, ShardingService_InsertDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardingServiceClient) QueryDocuments(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, ShardingService_QueryDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardingServiceClient) BulkInsert(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BulkInsertRequest, BulkInsertResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShardingService_ServiceDesc.Streams[0], ShardingService_BulkInsert_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BulkInsertRequest, BulkInsertResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShardingService_BulkInsertClient = grpc.ClientStreamingClient[BulkInsertRequest, BulkInsertResponse]

func (c *shardingServiceClient) WatchUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchRequest, WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShardingService_ServiceDesc.Streams[1], ShardingService_WatchUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShardingService_WatchUpdatesClient = grpc.BidiStreamingClient[WatchRequest, WatchEvent]

// ShardingServiceServer is the server API for ShardingService service.
// All implementations must embed UnimplementedShardingServiceServer
// for forward compatibility.
//
// ShardingService provides high-performance access to the sharded MongoDB cluster.
type ShardingServiceServer interface {
	// InsertDocument inserts a single document (unary).
	InsertDocument(context.Context, *InsertRequest) (*InsertResponse, error)
	// QueryDocuments queries documents with a filter (unary).
	QueryDocuments(context.Context, *QueryRequest) (*QueryResponse, error)
	// BulkInsert accepts a stream of document batches for high-throughput ingestion.
	// Client sends batches of ~1000 docs, server responds with total count.
	BulkInsert(grpc.ClientStreamingServer[BulkInsertRequest, BulkInsertResponse]) error
	// WatchUpdates maintains a bidirectional stream for real-time change events.
	// Client sends watch filters, server streams matching change events.
	WatchUpdates(grpc.BidiStreamingServer[WatchRequest, WatchEvent]) error
	mustEmbedUnimplementedShardingServiceServer()
}

// UnimplementedShardingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardingServiceServer struct{}

func (UnimplementedShardingServiceServer) InsertDocument(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertDocument not implemented")
}
func (UnimplementedShardingServiceServer) QueryDocuments(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDocuments not implemented")
}
func (UnimplementedShardingServiceServer) BulkInsert(grpc.ClientStreamingServer[BulkInsertRequest, BulkInsertResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BulkInsert not implemented")
}
func (UnimplementedShardingServiceServer) WatchUpdates(grpc.BidiStreamingServer[WatchRequest, WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchUpdates not implemented")
}
func (UnimplementedShardingServiceServer) mustEmbedUnimplementedShardingServiceServer() {}
func (UnimplementedShardingServiceServer) testEmbeddedByValue()                         {}

// UnsafeShardingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardingServiceServer will
// result in compilation errors.
type UnsafeShardingServiceServer interface {
	mustEmbedUnimplementedShardingServiceServer()
}

func RegisterShardingServiceServer(s grpc.ServiceRegistrar, srv ShardingServiceServer) {
	// If the following call pancis, it indicates UnimplementedShardingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShardingService_ServiceDesc, srv)
}

func _ShardingService_InsertDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardingServiceServer).InsertDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardingService_InsertDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardingServiceServer).InsertDocument(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardingService_QueryDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardingServiceServer).QueryDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardingService_QueryDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardingServiceServer).QueryDocuments(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardingService_BulkInsert_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShardingServiceServer).BulkInsert(&grpc.GenericServerStream[BulkInsertRequest, BulkInsertResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShardingService_BulkInsertServer = grpc.ClientStreamingServer[BulkInsertRequest, BulkInsertResponse]

func _ShardingService_WatchUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShardingServiceServer).WatchUpdates(&grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShardingService_WatchUpdatesServer = grpc.BidiStreamingServer[WatchRequest, WatchEvent]

// ShardingService_ServiceDesc is the grpc.ServiceDesc for ShardingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sharding.v1.ShardingService",
	HandlerType: (*ShardingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertDocument",
			Handler:    _ShardingService_InsertDocument_Handler,
		},
		{
			MethodName: "QueryDocuments",
			Handler:    _ShardingService_QueryDocuments_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BulkInsert",
			Handler:       _ShardingService_BulkInsert_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchUpdates",
			Handler:       _ShardingService_WatchUpdates_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/sharding/v1/sharding.proto",
}
